config/routes.rb
Blog::Application.routes.draw do

  devise_for :users

  get "home/index"
  get "comments/index"
  get "comments/edit"
  get "comments/show"
  get "comments/create"
  
  menu = %w(hobby ruby_on_rails portfolio contact)
  menu.each{|item| match "/#{item}" => "#{item}#index"}

  resources :posts do
    resources :comments
  end
  
  resources :taxons
  resources :users
  

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content, :post_id, :user_id
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :title, :user_id
  
  has_many :comments
  
  MAX_NO_OF_WORDS_IN_INDEX = 20
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :users
end

app/models/taxon.rb
class Taxon < ActiveRecord::Base
  attr_accessible :description, :name, :parent_id, :permalink
  acts_as_tree

  scope :taxonomies, lambda{where("parent_id IS NULL")}
  scope :ordered, lambda{order(:created_at)}
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :avatar, :email, :password, :password_confirmation, :remember_me
  
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
  
  has_and_belongs_to_many :roles
  
  def is_admin?
    self.roles.include?(Role.find_by_name('admin'))
  end
  
  def is_user?
    self.roles.include?(Role.find_by_name('user'))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
  def check_access
    redirect_to root_path unless current_user && current_user.is_admin?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment])
    redirect_to post_path(@post)
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
    @taxons = Taxon.find_by_name('Contact').children.order(:name)
  end
end

app/controllers/hobby_controller.rb
class HobbyController < ApplicationController
  def index
    @taxons = Taxon.find_by_name('Hobby').children.order(:name)

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @taxons = Taxon.find_by_name('Home').children.order(:name)
  end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
    @taxons = Taxon.find_by_name('Portfolio').children.order(:name)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.order('created_at DESC')
    @taxons = Taxon.find_by_name('Blog').children.order(:name)
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def create
    post = Post.new(params[:post])
    
    if post.save
      redirect_to posts_path, :notice => 'You have created post successfully'
    else
      redirect_to posts_path, :error => 'Error occurred, please try again later'
    end
  end
  
  def new
    @post = Post.new
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(params[:post])
      redirect_to posts_path, :notice => 'Post was successfully updated.'
    else
      redirect_to posts_path, :notice => 'Error occurred, please try again later'
    end
  end
end

app/controllers/taxons_controller.rb
class TaxonsController < ApplicationController
  
  before_filter :check_access
  
  def index
    @taxons = Taxon.all
  end

  def edit
    @taxon = Taxon.find params[:id]
  end
  
  def update
    taxon = Taxon.find params[:id]
    
    if taxon.update_attributes params[:taxon]
      redirect_to :action => 'index', :notice => "You have successfully updated taxon!"
    else
      redirect_to :action => 'index', :notice => "Error occurred when updating taxon. Try again later."
    end
  end
  
  def create
    @taxon = Taxon.new params[:taxon]
    
    if @taxon.save
      redirect_to :action => 'index', :notice => "You have successfully created taxon!"   
    else
      redirect_to :action => 'index', :notice => "Error occurred when creating taxon. Try again later."
    end
  end

  def new
    @taxon = Taxon.new
  end

  def show
    @taxon = Taxon.find params[:id]
  end
  
  def destroy
    taxon = Taxon.find params[:id]
    if taxon.destroy
      redirect_to :action => 'index', :notice => "You have successfully deleted taxon"
    else
      redirect_to :action => 'index', :notice => "Error occurred when deleting taxon. Try again later."
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_access
  
  def index
    @users = User.all
  end
  
  def show
    @user = User.find_by_id(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/hobby_helper.rb
module HobbyHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def limited_post_content(post_content)
    length = post_content.split(' ').length
    limited_post_content = length > Post::MAX_NO_OF_WORDS_IN_INDEX ? post_content[/(\S+\s+){#{Post::MAX_NO_OF_WORDS_IN_INDEX}}/].strip : post_content
    limited_post_content += '...'
    limited_post_content
  end
  
  def link_to_post(post)
    comments_count = post.comments.count
    if comments_count > 0
      link_to "#{comments_count} Comment(s)", post_path(post), :class => 'comments'
    else
      link_to "No Comments", post_path(post), :class => 'comments'
    end
  end
end

app/helpers/ruby_on_rails_helper.rb
module RubyOnRailsHelper
end

app/helpers/taxon_helper.rb
module TaxonHelper
end

app/views/comments/_form.html.erb
<% form_for(@comment) do |c| %>
  <%= c.label :content %> 
<% end %>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |p| %>
  
  <div class="field">
    <%= p.label :title %><br/>
    <%= p.text_field :title %>
  </div>

  <div class="field">
    <%= p.label :content %><br/>
    <%= p.text_area :content %>
  </div>
  
  <%= p.submit %>
  
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render "form" %>

app/views/posts/index.html.erb
<% content_for :sidebar do %>
  <% if current_user && current_user.is_admin? %>
    <%= link_to "New Post", new_post_path, :class => "new_item_button" %>
  <% end %>

  <% @taxons.each do |taxon| %>
    <li><%= link_to taxon.name, taxon.permalink %></li>
  <% end %>
<% end %>

<% @posts.each do |post| %>
  <div class="post">
    <table id="post-header">
      <tr>
        <td>
          <h1 class="post-title"><%= link_to post.title, post_path(post) %></h1>
        </td>
        <td>
          <%= link_to "Edit", edit_post_path(post) if current_user && current_user.is_admin? %>
        </td>
      </tr>
    </table>
    <p class="post-content">
      <%= limited_post_content(post.content) %>
      <%= link_to "(read more)", post_path(post) %>
    </p>
    <p class="links">
      <%= link_to "Read More", post_path(post), :class => 'more' %> &nbsp;&nbsp;&nbsp; 
      <%= link_to_post(post) %>
    </p>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<div id="post-show">
  <table id="post-show-header">
    <tr>
      <td>
        <h1><%= @post.title %></h1>
      </td>
      <td><%= link_to "Edit", edit_post_path(@post) if current_user && current_user.is_admin? %></td>
    </tr>
  </table>
  

  <h4>Content:</h4>
  <%= @post.content %>

  <h4>Created at:</h4>
  <%= @post.created_at %>

  <h4>Updated at:</h4>
  <%= @post.updated_at %>
</div>

<%= link_to "Add comment", "#", :id => "add_comment", :remote => true %>

<div id="add_comment" class="visible">
  <%= form_for([@post, @post.comments.build]) do |f| %>
    <%= f.label :content %><br/>
    <%= f.text_area :content, :size => "60x6" %>
    
    <%= f.submit %>
  <% end %>
</div>

<br/><br/>

<div id="comments">
  <% if @post.comments.present? %>
    <% Rails.logger.info "=========== #{@post.comments.inspect}" %>
    <% @post.comments.each do |comment| %>
      <div class="comment">
        <%= comment.content %>
        <p>Commented at: <%= comment.created_at %></p>
      </div>
    <% end %>
  <% end %>
</div> 

app/views/taxons/_form.html.erb
<%= form_for(@taxon) do |f|%>
  <div class="form_field">
    <%= f.label :parent_id %>:<br/>
    <%#= f.select :parent_id, options_for_select((1..10)) %>
    <%= f.select :parent_id, options_for_select(Taxon.all.collect{|t| [t.name, t.id]}.insert(0, ["No parent", nil]), :select => @taxon.parent_id) %>
  </div>
  <div class="form_field">
    <%= f.label :name %>:<br/>
    <%= f.text_field :name %>
  </div>
  <div class="form_field">
    <%= f.label :permalink %>:<br/>
    <%= f.text_field :permalink %>
  </div>
  
  <%= f.submit %>
<% end %>

app/views/taxons/edit.html.erb
<h1>Taxon#edit</h1>
<p>Find me in app/views/taxon/edit.html.erb</p>

<%= render :partial => 'form', @taxon => @taxon %>

app/views/taxons/index.html.erb
<div>  
  <table>
    <tr>
      <td>
        <h1>Taxon#index</h1>
      </td>
       <td style="text-align: right;">
         <%= link_to "New Taxon", new_taxon_path, :class => 'new_item_button' %>
       </td>
    </tr>
  </table>
  <% if @taxons.present? %>
    <table id="taxon_table">
      <tr>
        <th>id</th>
        <th>parent_id</th>
        <th>name</th>
        <th>permalink</th>
        <th>description</th>
        <th>action links</th>
      </tr>
      <% @taxons.each do |taxon| %>
        <tr class="<%= cycle('odd', 'even') %>">
          <td><%= taxon.id %></td>
          <td><%= taxon.parent_id %></td>
          <td><%= taxon.name %></td>
          <td><%= taxon.permalink %></td>
          <td><%= taxon.description %></td>
          <td><%= link_to "Edit", edit_taxon_path(taxon) %></td>
          <td><%= link_to "Delete", taxon_path(taxon), :method => :delete %></td>
        </tr>
      <% end %>
    </table>
    
  <% else %>
    No taxon yet ...
  <% end %>
</div>
  

app/views/taxons/new.html.erb
<h1>Taxon#new</h1>
<p>Find me in app/views/taxon/new.html.erb</p>

<%= render 'form' %>

app/views/taxons/show.html.erb
<h1>Taxon#show</h1>
<p>Find me in app/views/taxon/show.html.erb</p>